spring:
  datasource:
    url: jdbc:mysql://localhost:3306/isuda
    username: root
    # TODO: delete when push
    password: p@ssw0rd
mybatis:
  mapper-locations: classpath://**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
